In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("student-data.csv")
df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher   
1       GP   F   17       U     GT3       T     1     1   at_home     other   
2       GP   F   15       U     LE3       T     1     1   at_home     other   
3       GP   F   15       U     GT3       T     4     2    health  services   
4       GP   F   16       U     GT3       T     3     3     other     other   
5       GP   M   16       U     LE3       T     4     3  services     other   
6       GP   M   16       U     LE3       T     2     2     other     other   
7       GP   F   17       U     GT3       A     4     4     other   teacher   
8       GP   M   15       U     LE3       A     3     2  services     other   
9       GP   M   15       U     GT3       T     3     4     other     other   
10      GP   F   15       U     GT3       T     4     4   teacher    health   
11      GP   F   15       U     GT3       T     2     1  services     other   
12      GP   M   15       U     LE3       T     4     4    health  services   
13      GP   M   15       U     GT3       T     4     3   teacher     other   
14      GP   M   15       U     GT3       A     2     2     other     other   
15      GP   F   16       U     GT3       T     4     4    health     other   
16      GP   F   16       U     GT3       T     4     4  services  services   
17      GP   F   16       U     GT3       T     3     3     other     other   
18      GP   M   17       U     GT3       T     3     2  services  services   
19      GP   M   16       U     LE3       T     4     3    health     other   
20      GP   M   15       U     GT3       T     4     3   teacher     other   
21      GP   M   15       U     GT3       T     4     4    health    health   
22      GP   M   16       U     LE3       T     4     2   teacher     other   
23      GP   M   16       U     LE3       T     2     2     other     other   
24      GP   F   15       R     GT3       T     2     4  services    health   
25      GP   F   16       U     GT3       T     2     2  services  services   
26      GP   M   15       U     GT3       T     2     2     other     other   
27      GP   M   15       U     GT3       T     4     2    health  services   
28      GP   M   16       U     LE3       A     3     4  services     other   
29      GP   M   16       U     GT3       T     4     4   teacher   teacher   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
365     MS   M   18       R     GT3       T     1     3   at_home     other   
366     MS   M   18       U     LE3       T     4     4   teacher  services   
367     MS   F   17       R     GT3       T     1     1     other  services   
368     MS   F   18       U     GT3       T     2     3   at_home  services   
369     MS   F   18       R     GT3       T     4     4     other   teacher   
370     MS   F   19       U     LE3       T     3     2  services  services   
371     MS   M   18       R     LE3       T     1     2   at_home  services   
372     MS   F   17       U     GT3       T     2     2     other   at_home   
373     MS   F   17       R     GT3       T     1     2     other     other   
374     MS   F   18       R     LE3       T     4     4     other     other   
375     MS   F   18       R     GT3       T     1     1     other     other   
376     MS   F   20       U     GT3       T     4     2    health     other   
377     MS   F   18       R     LE3       T     4     4   teacher  services   
378     MS   F   18       U     GT3       T     3     3     other     other   
379     MS   F   17       R     GT3       T     3     1   at_home     other   
380     MS   M   18       U     GT3       T     4     4   teacher   teacher   
381     MS   M   18       R     GT3       T     2     1     other     other   
382     MS   M   17       U     GT3       T     2     3     other  services   
383     MS   M   19       R     GT3       T     1     

In [3]:
df.shape

(395, 31)

In [20]:
n_students=df.shape[0]
n_features=df.shape[1]
passed = df.loc[df.passed == 'yes', 'passed']
n_passed = passed.shape[0]
failed = df.loc[df.passed == 'no', 'passed']
n_failed = failed.shape[0]
total = float(n_passed + n_failed)
grad_rate = float(n_passed * 100 / total)

print(n_students)
print(n_features)
print(n_passed)
print(n_failed)
print(total)
print(grad_rate)

395
31
265
130
395.0
67.0886075949367


In [21]:
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'passed'],
      dtype='object')

In [22]:
df.columns[-1]

'passed'

In [24]:
df.columns[:-1]

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences'],
      dtype='object')

In [26]:
feature_cols = list(df.columns[:-1])
target_col = df.columns[-1]


In [33]:
print(feature_cols)
print(target_col)

['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences']
passed


In [87]:
X=df.values[:, 0:5]
Y =df.values[:,6]

In [41]:
from sklearn.model_selection import train_test_split

In [123]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1)

In [124]:
X_train.shape

(296, 5)

In [125]:
y_train.shape

(296,)

In [126]:
X_test.shape

(99, 5)

In [127]:
y_test.shape

(99,)

In [120]:
print(X_train.shape[0])
print(X_test.shape[0])

304
91


In [95]:
 print(np.mean(y_train == 'no'))
print(np.mean(y_test == 'no'))

0.31666666666666665
0.3684210526315789


In [97]:
from sklearn import preprocessing

In [98]:
le = preprocessing.LabelEncoder()
df = df.apply(le.fit_transform)
df

school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob  ...  \
0         0    0    3        1        0        0     4     4     0     4  ...   
1         0    0    2        1        0        1     1     1     0     2  ...   
2         0    0    0        1        1        1     1     1     0     2  ...   
3         0    0    0        1        0        1     4     2     1     3  ...   
4         0    0    1        1        0        1     3     3     2     2  ...   
5         0    1    1        1        1        1     4     3     3     2  ...   
6         0    1    1        1        1        1     2     2     2     2  ...   
7         0    0    2        1        0        0     4     4     2     4  ...   
8         0    1    0        1        1        0     3     2     3     2  ...   
9         0    1    0        1        0        1     3     4     2     2  ...   
10        0    0    0        1        0        1     4     4     4     1  ...   
11        0    0    0        1        0        1     2     1     3     2  ...   
12        0    1    0        1        1        1     4     4     1     3  ...   
13        0    1    0        1        0        1     4     3     4     2  ...   
14        0    1    0        1        0        0     2     2     2     2  ...   
15        0    0    1        1        0        1     4     4     1     2  ...   
16        0    0    1        1        0        1     4     4     3     3  ...   
17        0    0    1        1        0        1     3     3     2     2  ...   
18        0    1    2        1        0        1     3     2     3     3  ...   
19        0    1    1        1        1        1     4     3     1     2  ...   
20        0    1    0        1        0        1     4     3     4     2  ...   
21        0    1    0        1        0        1     4     4     1     1  ...   
22        0    1    1        1        1        1     4     2     4     2  ...   
23        0    1    1        1        1        1     2     2     2     2  ...   
24        0    0    0        0        0        1     2     4     3     1  ...   
25        0    0    1        1        0        1     2     2     3     3  ...   
26        0    1    0        1        0        1     2     2     2     2  ...   
27        0    1    0        1        0        1     4     2     1     3  ...   
28        0    1    1        1        1        0     3     4     3     2  ...   
29        0    1    1        1        0        1     4     4     4     4  ...   
..      ...  ...  ...      ...      ...      ...   ...   ...   ...   ...  ...   
365       1    1    3        0        0        1     1     3     0     2  ...   
366       1    1    3        1        1        1     4     4     4     3  ...   
367       1    0    2        0        0        1     1     1     2     3  ...   
368       1    0    3        1        0        1     2     3     0     3  ...   
369       1    0    3        0        0        1     4     4     2     4  ...   
370       1    0    4        1        1        1     3     2     3     3  ...   
371       1    1    3        0        1        1     1     2     0     3  ...   
372       1    0    2        1        0        1     2     2     2     0  ...   
373       1    0    2        0        0        1     1     2     2     2  ...   
374       1    0    3        0        1        1     4     4     2     2  ...   
375       1    0    3        0        0        1     1     1     2     2  ...   
376       1    0    5        1        0        1     4     2     1     2  ...   
377       1    0    3        0        1        1     4     4     4     3  ...   
378       1    0    3        1        0        1     3     3     2     2  ...   
379       1    0    2        0        0        1     3     1     0     2  ...   
380       1    1    3        1        0        1     4     4     4     4  ...   
381       1    1    3        0        0        1     2     1     2     2  ...   
382       1    1    2        1      

In [139]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
import warnings
warnings.filterwarnings('ignore')

In [140]:
lg=LogisticRegression()

In [141]:
lg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [145]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
predrf=rf.predict(X_test)
print(accuracy_score(y_test,predrf))
print(confusion_matrix(y_test,predrf))
print(classification_report(y_test,predrf))

0.6161616161616161
[[ 7 24]
 [14 54]]
              precision    recall  f1-score   support

          no       0.33      0.23      0.27        31
         yes       0.69      0.79      0.74        68

    accuracy                           0.62        99
   macro avg       0.51      0.51      0.50        99
weighted avg       0.58      0.62      0.59        99



In [136]:
lg=LogisticRegression()
lg.fit(X_train,y_train)
predlg=lg.predict(X_test)
print(accuracy_score(y_test,predlg))
print(confusion_matrix(y_test,predlg))
print(classification_report(y_test,predlg))

0.6666666666666666
[[ 6 25]
 [ 8 60]]
              precision    recall  f1-score   support

          no       0.43      0.19      0.27        31
         yes       0.71      0.88      0.78        68

    accuracy                           0.67        99
   macro avg       0.57      0.54      0.53        99
weighted avg       0.62      0.67      0.62        99



In [137]:
gnb=GaussianNB()
gnb.fit(X_train,y_train)
predgnb=gnb.predict(X_test)
print(accuracy_score(y_test,predgnb))
print(confusion_matrix(y_test,predgnb))
print(classification_report(y_test,predgnb))

0.5858585858585859
[[ 4 27]
 [14 54]]
              precision    recall  f1-score   support

          no       0.22      0.13      0.16        31
         yes       0.67      0.79      0.72        68

    accuracy                           0.59        99
   macro avg       0.44      0.46      0.44        99
weighted avg       0.53      0.59      0.55        99



In [131]:
from sklearn.tree import DecisionTreeClassifier

In [132]:
dt=DecisionTreeClassifier()

In [133]:
dt.fit(X_train,y_train)
dt.score(X_train,y_train)
preddt=dt.predict(X_test)
print(accuracy_score(y_test,preddt))
print(confusion_matrix(y_test,preddt))
print(classification_report(y_test,preddt))

0.5656565656565656
[[ 9 22]
 [21 47]]
              precision    recall  f1-score   support

          no       0.30      0.29      0.30        31
         yes       0.68      0.69      0.69        68

    accuracy                           0.57        99
   macro avg       0.49      0.49      0.49        99
weighted avg       0.56      0.57      0.56        99



In [149]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [150]:
y_pred = svclassifier.predict(X_test)

In [154]:
from sklearn.metrics import classification_report, confusion_matrix
svclassifier.score(X_train, y_train)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))


[[ 0 31]
 [ 0 68]]
              precision    recall  f1-score   support

          no       0.00      0.00      0.00        31
         yes       0.69      1.00      0.81        68

    accuracy                           0.69        99
   macro avg       0.34      0.50      0.41        99
weighted avg       0.47      0.69      0.56        99

0.6868686868686869
